### ISSUE TITLE
Can't specify Etcd host using IP address when using TLS

### ISSUE THREAD

**Issue by alexander-stepanov** [rabbitmq/rabbitmq-peer-discovery-etcd#11]
The plugin is unable to connect to the Etcd backend if the host is specified using IP address and Etcd is configured to use TLS, e.g. with config like:
```
cluster_formation.etcd.host = 10.100.1.184
cluster_formation.etcd.port = 2379
cluster_formation.etcd.scheme = https
```
I get an error:
```
2018-05-24 14:35:16.819 [error] <0.188.0> Failed to lock with peer discovery backend rabbit_peer_discovery_etcd: "Error while acquiring the lock, reason: \"{failed_connect,[{to_address,{\\\"10.100.1.184\\\",2379}},\\n                 {inet,[inet],\\n                       {options,{{server_name_indication,\\\"10.100.1.184\\\"}}}}]}\""
```
But when I use a FQDN in cluster_formation.etcd.host which resolves to the same IP address, it works correctly.

**Comment by lukebakken** [comment]
The HTTP client used to make requests to `etcd` appears to require a host name when `https` is used to verify that the server's certificate matches the host name (known as ["Server Name Indication"](https://en.wikipedia.org/wiki/Server_Name_Indication)). It appears that using a host name will be a requirement (@michaelklishin)

**Comment by michaelklishin** [comment]
SNI is actually orthogonal to hostname-based peer verification strategies widely used by TLS clients.

There is no evidence that there's anything missing in this plugin. As @lukebakken points out, target hostname or IP address with HTTPS will have to match that of the certificate used by the server. If it doesn't, a failure is expected. There's [an entire guide on TLS troubleshooting](http://www.rabbitmq.com/troubleshooting-ssl.html) and a lot of it applies to this plugin, too.

**Comment by michaelklishin** [comment]
There's also [an entire guide on network troubleshooting](https://www.rabbitmq.com/troubleshooting-networking.html) that is relevant here. The plugin doesn't do anything sophisticated beyond computing full URLs from the config values and issuing HTTP `GET`/`PUT`/`DELETE` requests against them. HTTP clients are very rarely responsible for connectivity issues. Other layers of the network (including TLS) are, and that guide describes a methodology that helps narrow the problem down efficiently.

**Comment by alexander-stepanov** [comment]
When debugging this issue I've noticed that even a simple https connection from Erlang to Etcd wasn't successful.
E.g. running the following snippet from the `erl` shell gave me a "failed connection":
```
inets:start().
ssl:start().
httpc:request("https://10.100.1.184:2379").
```
The problem was solved by upgrading Erlang/OTP packages to the latest 20.3.2 version I've got from the Alpine's edge repository.

**Comment by michaelklishin** [comment]
So there potentially was a non-standard OTP distribution involved. Thanks for reporting back.

FTR, 20.3.2 is not the latest version of OTP, 20.3.7 is.
