### ISSUE TITLE
rabbitmqctl cluster_status only show local node

### ISSUE THREAD

**Issue by binooetomo** [rabbitmq/rabbitmq-peer-discovery-etcd#8]
Dear All.
I have 3 vm with etcd and rabbitmq 3.7.3 in each vm.

etcd is clustered.

> root@encoder01 /home/bino# etcdctl member list
> 929319db57b8e24b: name=commander peerURLs=http://172.16.243.3:2380 clientURLs=http://172.16.243.3:2379 isLeader=false
> b63ad470a964f192: name=encoder01 peerURLs=http://172.16.243.129:2380 clientURLs=http://172.16.243.129:2379 isLeader=false
> f58085128fa482e5: name=web peerURLs=http://172.16.243.1:2380 clientURLs=http://172.16.243.1:2379 isLeader=true
> 

and healty

> root@encoder01 /home/bino# etcdctl cluster-health
> member 929319db57b8e24b is healthy: got healthy result from http://172.16.243.3:2379
> member b63ad470a964f192 is healthy: got healthy result from http://172.16.243.129:2379
> member f58085128fa482e5 is healthy: got healthy result from http://172.16.243.1:2379
> cluster is healthy
> 

rabbitmq clustering looks succed in registering to etcd

> root@encoder01 /home/bino# etcdctl ls --recursive
> /discovery_rbmqdml
> /discovery_rbmqdml/rbcluster_dml
> /discovery_rbmqdml/rbcluster_dml/nodes
> /discovery_rbmqdml/rbcluster_dml/nodes/rabbit@web
> /discovery_rbmqdml/rbcluster_dml/nodes/rabbit@encoder01
> /discovery_rbmqdml/rbcluster_dml/nodes/rabbit@commander
> 

but somehow , rabbitmqctl cluster_status only show 1 node

> root@encoder01 /home/bino# rabbitmqctl cluster_status
> Cluster status of node rabbit@encoder01 ...
> [{nodes,[{disc,[rabbit@encoder01]}]},
>  {running_nodes,[rabbit@encoder01]},
>  {cluster_name,<<"rabbit@encoder01">>},
>  {partitions,[]},
>  {alarms,[{rabbit@encoder01,[]}]}]
> 
> 

> root@web /etc/rabbitmq# rabbitmqctl cluster_status
> Cluster status of node rabbit@web ...
> [{nodes,[{disc,[rabbit@web]}]},
>  {running_nodes,[rabbit@web]},
>  {cluster_name,<<"rabbit@web">>},
>  {partitions,[]},
>  {alarms,[{rabbit@web,[]}]}]
> 

> root@commander /etc/rabbitmq# rabbitmqctl cluster_status
> Cluster status of node rabbit@commander ...
> [{nodes,[{disc,[rabbit@commander]}]},
>  {running_nodes,[rabbit@commander]},
>  {cluster_name,<<"rabbit@commander">>},
>  {partitions,[]},
>  {alarms,[{rabbit@commander,[]}]}]
> 

Note : I have exactly same value of /etc/rabbitmq/rabbitmq.conf for all nodes

```
cluster_formation.peer_discovery_backend = rabbit_peer_discovery_etcd
cluster_formation.etcd.host = 127.0.0.1
cluster_formation.etcd.key_prefix = discovery_rbmqdml
cluster_formation.etcd.cluster_name = rbcluster_dml
cluster_formation.node_type = disc

```

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
There is a paragraph that explains when peer discovery will not be performed [in the docs](http://www.rabbitmq.com/cluster-formation.html) as well as [a section on troubleshooting](http://www.rabbitmq.com/cluster-formation.html#troubleshooting-cluster-formation).

I'm 99% certain that all nodes believe that they are (single node) cluster members already. Reset and restart two out of three and see their logs.
