### ISSUE TITLE
Process <0.213.0> with 0 neighbours crashed with reason: no function clause matching httpc_handler:socket_type

### ISSUE THREAD

**Issue by worp1900** [rabbitmq/rabbitmq-peer-discovery-etcd#9]
What could be my issue here?

I am freshly getting this issue when trying to run rabbitmq with an etcd backend.

Config:

    # The standard config that each cluster member gets
    default_user = my_user
    default_pass = my_pw

    cluster_formation.peer_discovery_backend = rabbit_peer_discovery_etcd
    cluster_formation.etcd.host = etcd_master
    # 2379 is used by default
    cluster_formation.etcd.port = 2379
    # http is used by default
    cluster_formation.etcd.scheme = http

Issue:

    rabbitmq_rabbit1.1.q5e5kz9ew0i5@test-010    | 2018-05-03 19:00:04.924 [error] <0.213.0> CRASH REPORT Process <0.213.0> with 0 neighbours crashed with reason: no function clause matching httpc_handler:socket_type({request,#Ref<0.3721194380.1824522241.107070>,<0.193.0>,0,'httploopback_users.guest = false',{"...",...},...}) line 1479
    rabbitmq_rabbit1.1.q5e5kz9ew0i5@test-010    | 2018-05-03 19:00:04.925 [error] <0.156.0> Supervisor httpc_handler_sup had child undefined started with {httpc_handler,start_link,undefined} at <0.213.0> exit with reason no function clause matching httpc_handler:socket_type({request,#Ref<0.3721194380.1824522241.107070>,<0.193.0>,0,'httploopback_users.guest = false',{"...",...},...}) line 1479 in context child_terminated

Removing the etcd plugin from the scenario, rabbitmq starts just fine by itself:

    2018-05-03 19:07:39.500 [info] <0.5.0> Server startup complete; 3 plugins started.

Rabbitmq can contact the etcd server on its hostname:

    PING etcd_master (XXX.XXX.XXX.XXX) 56(84) bytes of data.
    64 bytes from XXX.XXX.XXX.XXX: icmp_seq=1 ttl=64 time=0.022 ms
    64 bytes from XXX.XXX.XXX.XXX: icmp_seq=2 ttl=64 time=0.035 ms
    64 bytes from XXX.XXX.XXX.XXX: icmp_seq=3 ttl=64 time=0.037 ms
    --- etcd_master ping statistics ---
    3 packets transmitted, 3 received, 0% packet loss, time 2004ms
    rtt min/avg/max/mdev = 0.022/0.031/0.037/0.008 ms

Can't make anything of the error messages sadly, any help is greatly appreciated!

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
The only thing that can be suggested with this much information is that the exception comes from the HTTP client used by this plugin. [Enable debug logging](http://www.rabbitmq.com/cluster-formation.html#troubleshooting-cluster-formation) and see what requests it attempts to make.

One thing that stands out compared to [similar exceptions found on the Web](https://github.com/emqtt/emqttd/issues/1427) is that the scheme seems to be `httploopback_users.guest = false`, which seems to be two lines concatenated. I don't recall cases like this with the new config format.

If you plan on using http and default port then you can just leave those two out.

The rest of the investigation belongs to rabbitmq-users.

**Comment by michaelklishin** [comment]
I tried two config files (and reset both nodes and my local etcd node between tries):

``` conf
cluster_formation.peer_discovery_backend = rabbit_peer_discovery_etcd

cluster_formation.etcd.host = localhost
cluster_formation.etcd.scheme = http

log.file.level = debug
log.console.level = debug

```

and 

``` conf
default_user = guest
default_pass = guest

cluster_formation.peer_discovery_backend = rabbit_peer_discovery_etcd

cluster_formation.etcd.host = etcd_master
cluster_formation.etcd.port = 2379
cluster_formation.etcd.scheme = http
```

and cannot reproduce. One example has a trailing newline, the other doesn't, so I'm not sure how anything can be concatenated with `http` unless e.g. the config wasn't generated correctly.

**Comment by worp1900** [comment]
Your newline idea brought the solution for me:

My config file now reads:

    # The standard config that each cluster member gets
    default_user = someName
    default_pass = somePw

    cluster_formation.peer_discovery_backend = rabbit_peer_discovery_etcd
    cluster_formation.etcd.host = etcd_master
    # 2379 is used by default
    cluster_formation.etcd.port = 2379
    # http is used by default
    cluster_formation.etcd.scheme = http

The result:

    rabbitmq_rabbit1.1.f9ypst3fnvxn@test-010    | 2018-05-08 18:28:53.378 [info] <0.33.0> Application rabbit started on node rabbit@rabbit1
    rabbitmq_rabbit1.1.f9ypst3fnvxn@test-010    | 2018-05-08 18:28:53.378 [info] <0.469.0> Peer discovery: node cleanup is disabled
    rabbitmq_rabbit1.1.f9ypst3fnvxn@test-010    | 2018-05-08 18:28:53.378 [info] <0.33.0> Application rabbitmq_peer_discovery_common started on node rabbit@rabbit1
    rabbitmq_rabbit1.1.f9ypst3fnvxn@test-010    | 2018-05-08 18:28:53.379 [info] <0.474.0> Starting etcd health check notifier (effective interval: 30 milliseconds)
    rabbitmq_rabbit1.1.f9ypst3fnvxn@test-010    | 2018-05-08 18:28:53.379 [info] <0.33.0> Application rabbitmq_peer_discovery_etcd started on node rabbit@rabbit1
    rabbitmq_rabbit1.1.f9ypst3fnvxn@test-010    | 2018-05-08 18:28:53.381 [info] <0.33.0> Application rabbitmq_management_agent started on node rabbit@rabbit1
    rabbitmq_rabbit1.1.f9ypst3fnvxn@test-010    | 2018-05-08 18:28:53.381 [info] <0.33.0> Application rabbitmq_web_dispatch started on node rabbit@rabbit1
    rabbitmq_rabbit1.1.f9ypst3fnvxn@test-010    | 2018-05-08 18:28:53.408 [info] <0.522.0> Management plugin started. Port: 15672
    rabbitmq_rabbit1.1.f9ypst3fnvxn@test-010    | 2018-05-08 18:28:53.409 [info] <0.628.0> Statistics database started.
    rabbitmq_rabbit1.1.f9ypst3fnvxn@test-010    | 2018-05-08 18:28:53.409 [info] <0.33.0> Application rabbitmq_management started on node rabbit@rabbit1
    rabbitmq_rabbit1.1.f9ypst3fnvxn@test-010    | 2018-05-08 18:28:53.573 [info] <0.5.0> Server startup complete; 5 plugins started.
    rabbitmq_rabbit1.1.f9ypst3fnvxn@test-010    |  * rabbitmq_management
    rabbitmq_rabbit1.1.f9ypst3fnvxn@test-010    |  * rabbitmq_web_dispatch
    rabbitmq_rabbit1.1.f9ypst3fnvxn@test-010    |  * rabbitmq_management_agent
    rabbitmq_rabbit1.1.f9ypst3fnvxn@test-010    |  * rabbitmq_peer_discovery_etcd
    rabbitmq_rabbit1.1.f9ypst3fnvxn@test-010    |  * rabbitmq_peer_discovery_common
    rabbitmq_rabbit1.1.f9ypst3fnvxn@test-010    |  completed with 5 plugins.

However, I was triggered by the fact that I don't remember setting the loopback_users.guest config anywhere, so I went back in the Image chain and found it here:
rabbitmq:3.7 image contains 
`rabbit_set_config 'loopback_users.guest' 'false'`
in line 266 of its docker-entrypoint.sh script:
https://github.com/docker-library/rabbitmq/blob/1a37166704d2ca7c386980387e81615985d5db47/3.7/debian/docker-entrypoint.sh

It also strikes me as a coincidence that it's the first call to `rabbit_set_config` that gets executed in that file.

Might it be the case that this function puts a new line every time it sets a new config param but neglects to first put a new line before its first call?

**Comment by michaelklishin** [comment]
I see no evidence of any issues with this plugin. The Docker image is maintained by Docker folks and there is nothing related to that image in this repo.
